openapi: 3.0.0
info:
  title: Interest Knowledge API
  version: "1.0"
paths:
  /update:
    post:
      summary: Aggiorna i dati nel knowledge base
      operationId: updateKnowledge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                progetti:
                  type: array
                  items:
                    type: object
                    properties:
                      nome:
                        type: string
                      partner:
                        type: array
                        items:
                          type: string
                      target:
                        type: string
                      note:
                        type: string
      responses:
        "200":
          description: Dato aggiornato con successo
